name: CI/CD Pipeline Complète

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

    # Add pull request approval check
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:

  # Étape 1: Pr Approval Check
  check-pr-approval:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    steps:
      - name: Check PR Approval
        uses: actions/github-script@v6
        with:
          script: |
            const { data: reviews } = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const approved = reviews.some(review => review.state === 'APPROVED');
            if (!approved) {
              core.setFailed('Pull request needs to be approved first');
            }
  # Étape 2: Tests Backend
  backend-tests:
    needs: [check-pr-approval]
    if: always() && (needs.check-pr-approval.result == 'success' || github.event_name == 'push')
    name: Tests Backend & Coverage
    uses: ./.github/workflows/backend-tests-coverage.yml
    secrets: inherit

  # Étape 3: Tests Frontend
  frontend-tests:
   needs: [check-pr-approval]
   if: always() && (needs.check-pr-approval.result == 'success' || github.event_name == 'push')
   name: Tests Frontend & Coverage
   uses: ./.github/workflows/frontend-tests-coverage.yml
   secrets: inherit

  # Étape 4: Analyse Qualité Backend (déclenchée si tests OK)
  sonar-backend:
    name: SonarCloud Backend
    needs: [backend-tests, frontend-tests]
    if: always() && needs.backend-tests.result == 'success' && needs.frontend-tests.result == 'success'
    uses: ./.github/workflows/sonarcloud_back.yml
    secrets: inherit

  # Étape 5: Analyse Qualité Frontend (déclenchée si tests OK)
  sonar-frontend:
    name: SonarCloud Frontend
    needs: [backend-tests, frontend-tests]
    if: always() && needs.backend-tests.result == 'success' && needs.frontend-tests.result == 'success'
    uses: ./.github/workflows/sonarcloud_front.yml
    secrets: inherit

  # Étape 6: Build & Push Docker (déclenchée si qualité OK)
  docker-build:
    name: Build & Push Docker
    needs: [sonar-backend, sonar-frontend]
    if: always() && needs.sonar-backend.result == 'success' && needs.sonar-frontend.result == 'success'
    uses: ./.github/workflows/docker.yml
    secrets: inherit