name: SonarCloud Front (Quality)

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Frontend:
    name: Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Run npm install
        run: npm install
      
      # --- FIX IS HERE ---
      - name: Build and analyse
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_FRONT }}
        with:
         projectBaseDir: front
         args: >
            -Dsonar.projectKey=tesfayande_project_10_front
            -Dsonar.organization=tesfayande
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions=**/node_modules/**,**/tests/**,**/*.test.js,**/*.spec.js,**/src/setupTests.js
            -Dsonar.coverage.exclusions=**/node_modules/**,**/tests/**,**/*.test.js,**/*.spec.js,**/src/setupTests.js
            -Dsonar.sourceEncoding=UTF-8
